defaults:
- output/default
- _self_
generations: ???
workers: null
hydra:
  run:
    dir: ${generations_output:evaluate,${generations}}
  sweep:
    dir: outputs/evaluate
    subdir: ${generations_subdir:evaluate,${generations}}
